// insertBranches.js
const mongoose = require('mongoose');
const Branch = require('../models/Branch');

const branches = [
    { branch_name: "Aerospace Engineering", branch_code: "AE" },
    { branch_name: "Chemical Engineering", branch_code: "CHE" },
    { branch_name: "Civil Engineering", branch_code: "CE" },
    { branch_name: "Computer Science Engineering", branch_code: "CSE" },
    { branch_name: "Electrical Engineering", branch_code: "EE" },
    { branch_name: "Electronics & Communication Engineering", branch_code: "ECE" },
    { branch_name: "Mechanical Engineering", branch_code: "ME" },
    { branch_name: "Biomedical Engineering", branch_code: "BME" },
    { branch_name: "Automobile Engineering", branch_code: "AUE" },
    { branch_name: "Industrial Engineering", branch_code: "IE" },
    { branch_name: "Marine Engineering", branch_code: "MRE" },
    { branch_name: "Petroleum Engineering", branch_code: "PE" },
    { branch_name: "Metallurgical Engineering", branch_code: "MTE" },
    { branch_name: "Instrumentation Engineering", branch_code: "INE" },
    { branch_name: "Mechatronics Engineering", branch_code: "MTE" },
    { branch_name: "Environmental Engineering", branch_code: "ENE" },
    { branch_name: "Robotics Engineering", branch_code: "RE" },
    { branch_name: "Nanotechnology Engineering", branch_code: "NTE" },
    { branch_name: "Genetic Engineering", branch_code: "GE" },
    { branch_name: "Ceramic Engineering", branch_code: "CRE" },
    { branch_name: "Nuclear Engineering", branch_code: "NE" },
    { branch_name: "Agricultural Engineering", branch_code: "AGE" },
    { branch_name: "Mining Engineering", branch_code: "MIE" },
    { branch_name: "Textile Engineering", branch_code: "TE" },
    { branch_name: "Polymer Engineering", branch_code: "PE" },
    { branch_name: "Geological Engineering", branch_code: "GLE" },
    { branch_name: "Software Engineering", branch_code: "SE" },
    { branch_name: "Data Science Engineering", branch_code: "DSE" },
    { branch_name: "Cybersecurity Engineering", branch_code: "CSE" },
    { branch_name: "Artificial Intelligence Engineering", branch_code: "AIE" },
    { branch_name: "Machine Learning Engineering", branch_code: "MLE" },
    { branch_name: "Information Technology", branch_code: "IT" },
    { branch_name: "Chemical and Biological Engineering", branch_code: "CBE" },
    { branch_name: "Construction Engineering", branch_code: "CONE" },
    { branch_name: "Food Engineering", branch_code: "FE" },
    { branch_name: "Systems Engineering", branch_code: "SYSE" },
    { branch_name: "Renewable Energy Engineering", branch_code: "REE" },
    { branch_name: "Ocean Engineering", branch_code: "OE" },
    { branch_name: "Bioprocess Engineering", branch_code: "BPE" },
    { branch_name: "Hydraulic Engineering", branch_code: "HE" },
    { branch_name: "Structural Engineering", branch_code: "STE" },
    { branch_name: "Telecommunication Engineering", branch_code: "TCE" },
    { branch_name: "Power Systems Engineering", branch_code: "PSE" },
    { branch_name: "Production Engineering", branch_code: "PDE" },
    { branch_name: "Manufacturing Engineering", branch_code: "MFE" },
    { branch_name: "Mechatronics & Automation", branch_code: "MA" },
    { branch_name: "Transportation Engineering", branch_code: "TE" },
    { branch_name: "Urban Engineering", branch_code: "UE" },
    { branch_name: "Pulp and Paper Engineering", branch_code: "PPE" },
    { branch_name: "Tool Engineering", branch_code: "TOOLE" },
    { branch_name: "Medicine (M.B.B.S.)", branch_code: "MBBS" },
    { branch_name: "Dentistry (B.D.S.)", branch_code: "BDS" },
    { branch_name: "Pharmacy (B.Pharm./Pharm.D.)", branch_code: "BPHARM" },
    { branch_name: "Nursing", branch_code: "NURS" },
    { branch_name: "Physiotherapy", branch_code: "PT" },
    { branch_name: "Medical Laboratory Technology", branch_code: "MLT" },
    { branch_name: "Radiology", branch_code: "RAD" },
    { branch_name: "Ayurveda (B.A.M.S.)", branch_code: "BAMS" },
    { branch_name: "Homeopathy (B.H.M.S.)", branch_code: "BHMS" },
    { branch_name: "Public Health", branch_code: "PH" },
    { branch_name: "Dietetics & Nutrition", branch_code: "DN" },
    { branch_name: "Optometry", branch_code: "OPTM" },
    { branch_name: "Audiology", branch_code: "AUD" },
    { branch_name: "Occupational Therapy", branch_code: "OT" },
    { branch_name: "Speech & Language Therapy", branch_code: "SLT" },
    { branch_name: "Veterinary Medicine", branch_code: "VET" },
    { branch_name: "Prosthetics & Orthotics", branch_code: "PO" },
    { branch_name: "Cardiovascular Technology", branch_code: "CVT" },
    { branch_name: "Perfusion Technology", branch_code: "PFT" },
    { branch_name: "Respiratory Therapy", branch_code: "RT" },
    { branch_name: "Accounting", branch_code: "ACC" },
    { branch_name: "Finance", branch_code: "FIN" },
    { branch_name: "Marketing", branch_code: "MKT" },
    { branch_name: "Human Resources", branch_code: "HR" },
    { branch_name: "Operations Management", branch_code: "OM" },
    { branch_name: "International Business", branch_code: "IB" },
    { branch_name: "Supply Chain Management", branch_code: "SCM" },
    { branch_name: "Business Analytics", branch_code: "BA" },
    { branch_name: "Entrepreneurship", branch_code: "ENT" },
    { branch_name: "Project Management", branch_code: "PM" },
    { branch_name: "Retail Management", branch_code: "RM" },
    { branch_name: "Digital Marketing", branch_code: "DM" },
    { branch_name: "E-commerce", branch_code: "EC" },
    { branch_name: "Corporate Law", branch_code: "CL" },
    { branch_name: "Financial Planning", branch_code: "FP" },
    { branch_name: "Investment Banking", branch_code: "IB" },
    { branch_name: "Risk Management", branch_code: "RM" },
    { branch_name: "Actuarial Science", branch_code: "AS" },
    { branch_name: "Taxation", branch_code: "TAX" },
    { branch_name: "Public Relations", branch_code: "PR" },
    { branch_name: "Law (LL.B.)", branch_code: "LLB" },
    { branch_name: "Journalism & Mass Communication", branch_code: "JMC" },
    { branch_name: "Hotel Management", branch_code: "HM" },
    { branch_name: "Architecture", branch_code: "ARCH" },
    { branch_name: "Fine Arts", branch_code: "FA" },
    { branch_name: "Psychology", branch_code: "PSY" },
    { branch_name: "Sociology", branch_code: "SOC" },
    { branch_name: "Geology", branch_code: "GEO" },
    { branch_name: "Meteorology", branch_code: "MET" },
    { branch_name: "Astronomy", branch_code: "ASTRO" }
];

async function insertBranches() {
    try {
        await Branch.insertMany(branches);
        console.log('✅ 100 branches inserted successfully');
    } catch (error) {
        console.error('Error inserting branches:', error);
    }
}

module.exports = insertBranches;